# Generated by Django 4.2.9 on 2024-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('procedimento', models.CharField(choices=[('LP', 'Limpeza de Pele'), ('SB', 'Sombrancelhas'), ('CL', 'Cílios'), ('MF', 'Massagem Facial'), ('MC', 'Massagem Corporal'), ('DP', 'Depilaçaõ'), ('CC', 'Corte de cabelo')], default='SB', max_length=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem do procedimento')),
            ],
        ),
    ]
